# Site settings
title: Alper Kumcu
description: > # this means to ignore newlines until "baseurl:"
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://alperkumcu.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
