# Site settings
title: Alper Kumcu
email: 
description: > # this means to ignore newlines until "baseurl:"

# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jabranham.com" # the base hostname & protocol for your site
twitter_username: alperkumcu
github_username:  alperkumcu
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
