# Site settings
title: Alper Kumcu
email: alperkumcu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hello world!
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://alperkumcu.com" # the base hostname & protocol for your site
twitter_username: alperkumcu
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
